### ISSUE TITLE
error in fudge setup command: use_2to3 is invalid

### ISSUE THREAD

**Issue by ClaudiuCreanga** [fudge-py/fudge#13]
Can't use fudge with the latest setuptools >= 58 because use_2to3 is invalid.

**Comment by quantoid** [comment]
@kumar303 any chance of a fix for this? 

Can't install fudge on python 3.9.10 which is a shame because it's my favourite mocking package and changing to another would be a lot of work.

**Comment by quantoid** [comment]
Note that pinning python to 3.9.6 or 3.8 fixes the problem for now.

**Comment by ford--prefect** [comment]
The `use_2to3` statement is deprecated and not supported in setuptools>57.5. Either downgrade setuptools or find a way in the setup.py to get rid of the statement.
EDIT: just removing the statement from the setup.py works for me. Also note, that PEP517/518 deprecate setuptools and introduce a new way of building python projects.

**Comment by zeinramadan** [comment]
> Either downgrade setuptools or find a way in the setup.py to get rid of the statement

Used this command to downgrade setuptools version 57.4.0 and it finally worked. Thanks.
`pip install 'setuptools<57.5'`

**Comment by Stealthii** [comment]
PR #14 makes an attempt to have this fixed within the project, by providing `setup_requires` hints, and a pyproject.toml to inform PEP 518 builders about the setuptools requirement ([which is actually <58, so v57.5 is fine](https://setuptools.pypa.io/en/latest/history.html#v58-0-0)).

If your project still requires fudge and you want this resolvable in your PEP 518 build environment, you can install directly from the head of that PR (using sha if you want to ensure no changes):
```console
❯ uv init -p 3.9 fudge-pr14
Initialized project `fudge-pr14` at `/Users/stealthii/scratch/fudge-pr14`
❯ cd fudge-pr14
❯ uv add git+https://github.com/Stealthii/fudge --rev 63ef1efdddbc1296637285adb8e978b330d490c0
Using CPython 3.9.20 interpreter at: /opt/homebrew/opt/python@3.9/bin/python3.9
Creating virtual environment at: .venv
 Updated https://github.com/Stealthii/fudge (63ef1ef)
Resolved 2 packages in 65ms
Installed 1 package in 13ms
 + fudge==1.1.1 (from git+https://github.com/Stealthii/fudge@63ef1efdddbc1296637285adb8e978b330d490c0)
```
