### ISSUE TITLE
Mocking HTTPServer

### ISSUE THREAD

**Issue by Nachtfeuer** [fudge-py/fudge#4]
**Why does this not work?**

I have a simple application class and the run method does create
an instance of the HTTPServer passing the parameters as shown here
and calls serve_forever.

I can print the mocked_object and it's a fake for the HTTPServer but
when calling run the test does hang. **The real HTTPServer has been
instantiated instead waiting on port 8081.**

What did I wrong? A bug?

```
    cls = ["BaseHTTPServer.HTTPServer", "http.server.HTTPServer"][sys.version_info.major-2] 
    with patch(cls) as mocked_object: 
        mocked_object \ 
            .remember_order() \ 
            .expects("__init__").with_args(("127.0.0.1", 8081), request_handler) \ 
            .expects("serve_forever").with_args() 

        app = application() 
        app.run("127.0.0.1", 8081)
```

**Comment by jsatt** [comment]
@Nachtfeuer, You probably need to use the path to the module which you are importing HTTPServer into.

``` python
with patch('mymodule.HTTPServer') as mocked_object:
```

When you import HTTPServer into your module (which happens before you mock it) Python creates a reference to the class in memory. The mocking then changes the reference in the source location to the mocked object, leaving your imported reference unmocked. Using you modules path changes the reference that the code under test is using.

**Comment by Nachtfeuer** [comment]
Well but that's exactly what I did.
See my code ... I used: "BaseHTTPServer.HTTPServer" (for Python 2.x)

Here a simple example which does not work same way;

## Two simple modules (all in same folder)

_cat bar.py_

```
class Bar(object):
    def __init__(self):
        print("Bar.__init__ called")
```

_cat foo.py_

```
from bar import Bar

class Foo(object):
    def __init__(self):
        print("Foo.__init__ called") 
        self.bar = Bar()
```

## Now the test code

 _cat test.py_

```
from fudge import patch
from foo import Foo

class Bar2(object):
    def __init__(self):
        print("Bar2.__init__ called") 

class Foo2(object):
    def __init__(self):
        print("Foo2.__init__ called") 
        self.bar = Bar2()

print("foo and bar in the same file")
with patch("__main__.Bar2") as mocked_object:
    mocked_object.expects("__init__").with_args()
    foo = Foo2()

print("foo and bar in separate modules")
with patch("bar.Bar") as mocked_object:
    mocked_object.expects("__init__").with_args()
    foo = Foo()
```

## Here the test result

The "all in one file" test works fine but the modules test fail.
You can see from the output that the assertion is wrong since
the relating "**init**" are really called.

It might be related to my question (issue) ....

_python test.py_

```
foo and bar in the same file
Foo2.__init__ called
foo and bar in separate modules
Foo.__init__ called
Bar.__init__ called
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    foo = Foo()
  File "/tmp/test/local/lib/python2.7/site-packages/fudge/patcher.py", line 112, in __exit__
    fudge.verify()
  File "/tmp/test/local/lib/python2.7/site-packages/fudge/__init__.py", line 129, in verify
    registry.verify()
  File "/tmp/test/local/lib/python2.7/site-packages/fudge/__init__.py", line 95, in verify
    exp.assert_called()
  File "/tmp/test/local/lib/python2.7/site-packages/fudge/__init__.py", line 453, in assert_called
    raise AssertionError("%s was not called" % (self))
AssertionError: fake:bar.Bar.__init__() was not called
```

**Comment by jsatt** [comment]
@Nachtfeuer, you're still patching the object at it's source, instead of in the module it's being used in. 

Your test should look like this.

``` python
with patch("foo.Bar") as mocked_object:  # patch the imported foo.Bar, not the source bar.Bar
    mocked_object.expects("__init__").with_args()
    foo = Foo()
```
