### ISSUE TITLE
Not clear how to use fudge.patch with pytest

### ISSUE THREAD

**Issue by quantoid** [fudge-py/fudge#8]
I've started using **pytest** and want to continue using **fudge** rather than **mock** because I prefer the way fudge lets you declare expected calls and returns in once place.

However, when you `@fudge.patch` a test function, pytest interprets the function parameter as a fixture and raises an exception when it can't find one.

    @patch('some.other.thing')
    def test_something(fake_thing):
        fake_thing.expects('count').returns(123)
        result = something()
        assert result == 123

Running pytest raises:

    E       fixture 'fake_thing' not found

It's not clear from the fudge documentation how to use `fudge.patch` with pytest (search shows pytest is not mentioned anywhere).

**Comment by quantoid** [comment]
See also [StackOverflow question](https://stackoverflow.com/questions/49441970/how-to-use-fudge-patch-with-pytest) on this.

**Comment by quantoid** [comment]
Declaring a fixture that returns a `Fake` works okay:

    @fixture
    def request(monkeypatch):
        """
        Fake Session.request method so tests can mock expected REST requests.
        """
        fake_request = Fake()
        monkeypatch.setattr('requests.sessions.Session.request', fake_request)
        yield fake_request
        verify()

Then you test function gets this fake request and can set its own expectations before doing the test.

However, you have to do this for each thing you want to patch with a `Fake`, which seems clunky.

**Comment by quantoid** [comment]
Hmm, you can't use `verify` in each mock fixture (see comment above) because it would get called more than once if a test used more than one mock. 

You can't use `@fudge.test` on test functions because fixtures get created before the test function gets called, so when the test is called the decorator resets all the Fakes that were created as fixtures. :(

This seems to work as an equivalent of `@fudge.test` around every function, although not entirely sure that it will always get used before any other fixtures:

    @fixture(scope="function", autouse=True)
    def fudge():
        """
        Makes sure any Fakes are reset before and verified after every test.
        """
        clear_expectations()
        clear_calls()
        yield
        verify()

**Comment by jsatt** [comment]
I've never personally been a fan of pytest and rarely have used it, and in researching this issue I'm beginning to remember why.

Because of the (completely non-pythonic) introspection magic that pytest uses, I don't think you're going to be able to use fudge the same way you can unittest or nose. The decorators that fudge provides are convenience wrappers to do much of the `clear_calls` and `verify` steps that you mention above. Since pytest isn't compatible with these standard decorators, you're going to need to do these steps manually. Another option would be to build a plugin for pytest (as seems to be the standard for the pytest community) which provides these conveniences or provides a pytest compatible wrapping.

If there is an existing pytest-fudge plugin I'm not finding or one is created I'd be happy to add it's mention to the documentation. But I feel that since pytest is the library that is doing something out of the ordinary any other fix is outside of the scope of fudge.

**Comment by quantoid** [comment]
Fair enough, I tend to agree with you on pytest. However, in that case I think the documentation for fudge should make it clear that pytest is not supported, to save people wasting time trying to work out how to make them play well together.

**Comment by jsatt** [comment]
Good call. I'll think about that what that should look like and try to get something added later this week. And this issue should be get people by on Google searches in the mean time.

**Comment by jsatt** [comment]
@quantoid,
By the way, when I dug into to update the doc I realized that `@fudge.patch` can be used as a context manager as well.

```python
        >>> def test():
        ...     with fudge.patch('os.remove') as fake_remove:
        ...         fake_remove.expects_call()
        ...         # do stuff...
        ...
        >>> def test():
        ...     with fudge.patch('os.remove',
        ...                      'shutil.rmtree') as (fake_remove, fake_rmtree):
        ...         fake_remove.is_callable()
        ...         # do stuff...
```

**Comment by jwhitlock** [comment]
This means you could use ``fudge.patch`` as a pytest fixture:

```
@pytest.fixture
def fake_remove():
    with fudge.patch('os.remove') as fake_remove:
        yield fake_remove

def test(fake_remove):
    fake_remove.expects_call()
```

**Comment by quantoid** [comment]
Nice, but would that work with more than one fixture?

I suspect that using `fudge.patch` with multiple fixtures would get fudge confused because each one would clear calls and verify expectations.

**Comment by jsatt** [comment]
@quantoid I've been digging around in pytest a little more today. If you're using unittest.TestCase with pytest is doesn't do the dependency injection, so you can write your tests as you are used to. You're just not able to use a couple other pytest features, like parameterization, with the same tests. https://docs.pytest.org/en/latest/unittest.html#unittest-testcase
